[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 1_000_000
evm_version = "paris"
via_ir = true
fs_permissions = [{ access = "read", path = "./" }]

# RPCs nomeados (usados por forge script e cast)
[rpc_endpoints]
base-sepolia = "${RPC_BASE_SEPOLIA}"
base         = "${RPC_BASE}"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "short"
quote_style = "double"
number_underscore = "thousands"

# Perfis extras (ex.: CI mais estrito)
[profile.ci]
optimizer_runs = 20_000
via_ir = true